# Generated by Django 3.2.5 on 2021-08-11 07:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mail', '0002_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='home',
            name='user',
        ),
        migrations.AddField(
            model_name='home',
            name='user',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
